export const LOAD_CATEGORIES_INITIATE = 'LOAD_CATEGORIES_INITIATE';
export const LOAD_CATEGORIES_COMPLETE = 'LOAD_CATEGORIES_COMPLETE';
export const LOAD_CATEGORIES_FAILURE = 'LOAD_CATEGORIES_FAILURE';
