export const FETCH_POSTS_BY_CATEGORY_INIT = 'FETCH_POSTS_BY_CATEGORY_INIT';
export const FETCH_POSTS_BY_CATEGORY_SUCCESS =
  'FETCH_POSTS_BY_CATEGORY_SUCCESS';
export const FETCH_POSTS_BY_CATEGORY_FAILURE =
  'FETCH_POSTS_BY_CATEGORY_FAILURE';
export const SET_SORT_BY = 'SET_SORT_BY';
