export const LOAD_POST_DATA_INIT = 'LOAD_POST_DATA_INIT';
export const LOAD_POST_DATA_SUCCESS = 'LOAD_POST_DATA_SUCCESS';
export const LOAD_POST_DATA_FAILURE = 'LOAD_POST_DATA_FAILURE';
export const UPDATE_POST_DATA_INIT = 'UPDATE_POST_DATA_INIT';
export const UPDATE_POST_DATA_SUCCESS = 'UPDATE_POST_DATA_SUCCESS';
export const UPDATE_POST_DATA_FAILURE = 'UPDATE_POST_DATA_FAILURE';
