export const LOAD_COMMENT_DATA_INIT = 'LOAD_COMMENT_DATA_INIT';
export const LOAD_COMMENT_DATA_SUCCESS = 'LOAD_COMMENT_DATA_SUCCESS';
export const LOAD_COMMENT_DATA_FAILURE = 'LOAD_COMMENT_DATA_FAILURE';
export const UPDATE_COMMENT_DATA_INIT = 'UPDATE_COMMENT_DATA_INIT';
export const UPDATE_COMMENT_DATA_SUCCESS = 'UPDATE_COMMENT_DATA_SUCCESS';
export const UPDATE_COMMENT_DATA_FAILURE = 'UPDATE_COMMENT_DATA_FAILURE';
